### ISSUE TITLE
Is there an issue with the fwdprop routine in mod_network.f90 ?

### ISSUE THREAD

**Issue by marcdegraef** [modern-fortran/neural-fortran#23]
Hi, I'm new to ML and I find your code very interesting and useful as I begin to learn how to program these networks.  I have one question regarding the fwdprop method in the mod_network module:  on line 116 you have:

        layers(n) % z = matmul(transpose(layers(n-1) % w), layers(n-1) % a) + layers(n) % b

I'm a bit confused on why you are using the weights matrix from layer n-1 along with the biases from layer n to compute the linear output of layer n... shouldn't we be using the w matrix for layer n here ?  Maybe I'm misunderstanding how layers are organized, but any clarification you could provide would be very much appreciated !

Regards, Marc.

**Comment by milancurcic** [comment]
Hi Marc,

Happy to answer. Each neuron has an activation (`a`) and a bias (`b`). Each connection between two neurons has a weight (`w`). 

Unlike some popular libraries like Keras, neural-fortran treats all layers (input, hidden, and output) with the same data structure, here it's `layer_type`. 

Consider a network with one input, one hidden, and one output layer. In neural-fortran, this is modeled as an array of 3 `layer_type` instances. The input data act as activations of the input layer, and the activations in the output layer become the output of the network.

Because the weights are for the connections and not the neurons, only the weights for the two layers (out of three total) are used, and the third one are unused. Similarly, the bias array (`b`) is only used in activating neurons, so this array is unused in the first (input) layer.

Regarding indexing, the choice of which layers have unused `w` and `b` is just convention and personal preference. This made most sense to me. So, to calculate the activation at layer n we do:

```
z(n) = sigmoid(a(n-1) * w(n-1) + b(n))
```

The layers could've been designed such that the weights for each layer activation are stored in the same index -- where the arrow ends rather than where it begins, see http://neuralnetworksanddeeplearning.com/images/tikz10.png -- but this convention was most intuitive to me.

Cheers,
milan

**Comment by marcdegraef** [comment]
Hi Milan,

thanks for the prompt reply!

OK, I see your point about personal preference in assigning the weights to layer n or n-1.  I just got confused because the theoretical papers I happened to be reading use the convention that the weights and biases belong to the same layer, causing an "off-by-one" difference in sub/super scripts with respect to your code. As an exercise, I'm going to re-derive the back-propagation equations using your convention.

Thanks!
Marc
